[package]
name = "bolt-sidecar"
version = "0.1.0"
edition = "2021"
default-run = "bolt-sidecar"

[dependencies]
# core
clap = { version = "4.5.4", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
axum = { version = "0.7", features = ["macros"] }
warp = "0.3.7"
futures = "0.3"

# crypto
blst = "0.3.12"
secp256k1 = { version = "0.29.0", features = ["rand"] }

# alloy
alloy-rpc-client = { version = "0.1.1", features = ["reqwest", "ws", "pubsub"] }
alloy-consensus = { version = "0.1.1", features = ["k256"] }
alloy-provider = { version = "0.1.1", features = ["ws"] }
alloy-signer = "0.1.1"
alloy-signer-local = "0.1.1"
alloy-transport = "0.1.1"
alloy-eips = "0.1.1"
alloy-transport-http = "0.1.1"
alloy-transport-ws = "0.1.1"
alloy-pubsub = "0.1.1"
alloy-rpc-types = "0.1.1"
alloy-rpc-types-trace = "0.1.1"
alloy-json-rpc = "0.1.1"
alloy-network = "0.1.1"
alloy-primitives = "0.7.1"
alloy-rlp = "0.3"

# reth
reth-primitives = { git = "https://github.com/paradigmxyz/reth", rev = "71c404d" }
# reth-provider = { git = "https://github.com/paradigmxyz/reth", rev = "71c404d" }

reqwest = "0.12"
ethereum-consensus = { git = "https://github.com/ralexstokes/ethereum-consensus", rev = "cf3c404" }
beacon-api-client = { git = "https://github.com/ralexstokes/ethereum-consensus", rev = "cf3c404" }

# types
partial-mpt = { git = "https://github.com/chainbound/partial-mpt", branch = "feat/alloy" }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.115"
parking_lot = "0.12.1"
async-trait = "0.1.79"
bytes = "1.6.0"
lru = "0.12.3"
hex = "0.4.3"

# utils
eyre = "0.6.12"
thiserror = "1.0"
rand = "0.8.5"

# tracing
tracing = "0.1.40"
tracing-subscriber = "0.3.18"

# commit-boost
cb-crypto = { git = "https://github.com/Commit-Boost/commit-boost-client" }
cb-common = { git = "https://github.com/Commit-Boost/commit-boost-client" }

[dev-dependencies]
alloy-node-bindings = "0.1.1"


[[bin]]
name = "bolt-sidecar"
path = "bin/sidecar.rs"
